In [5]:
import numpy as np


a=np.random.random((2,3,5)) #floats random positivos entre 0 y 1
a2=np.random.randint(0,100,(2,3,5)) #numeros rand enteros con el rango def de 0 a 100 y tamaño de array (2,3,5)
a3=np.random.randn(2,3,5) #floats rand que van de negativo a positivo 

print(a)
print("")
print(a2)
print("")
print(a3)

[[[0.72300147 0.03352864 0.83113338 0.20996249 0.42948818]
  [0.44553685 0.40930492 0.85795258 0.52537988 0.75929232]
  [0.2150231  0.91405876 0.27617818 0.86079784 0.48231296]]

 [[0.78999773 0.08711266 0.20395488 0.72608813 0.46268258]
  [0.49156184 0.37491033 0.28296177 0.86787031 0.21174015]
  [0.46476318 0.58332309 0.94468677 0.28008485 0.37703367]]]

[[[73 18 28 23 63]
  [ 4 33 65 29 91]
  [ 5 75 87 24 99]]

 [[20 69 45 33 29]
  [14 20 67  4 12]
  [88  9 17 73 35]]]
[[[-0.13860564  0.624894   -2.38652371  0.14340603 -0.59713999]
  [-0.6621711  -0.93003636  1.80600419  1.51515711  2.01622282]
  [ 0.21281673  1.1504513   0.78736537 -1.48118632  0.49748982]]

 [[ 0.96764947  0.47106356  0.37292354  2.20050822 -0.12528145]
  [ 0.30426731 -0.87154035  0.0291904   0.42957709  1.67567877]
  [ 1.81540963 -0.73191321 -0.30635624 -1.54258697  0.88036359]]]


In [11]:
b=np.full((5,3,2),1)

In [12]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [13]:
a.ndim==b.ndim

True

In [15]:
c=b.T

In [19]:
d=a+c

In [27]:
print(d)
print("")
print(a)

[[[1.72300147 1.03352864 1.83113338 1.20996249 1.42948818]
  [1.44553685 1.40930492 1.85795258 1.52537988 1.75929232]
  [1.2150231  1.91405876 1.27617818 1.86079784 1.48231296]]

 [[1.78999773 1.08711266 1.20395488 1.72608813 1.46268258]
  [1.49156184 1.37491033 1.28296177 1.86787031 1.21174015]
  [1.46476318 1.58332309 1.94468677 1.28008485 1.37703367]]]

[[[0.72300147 0.03352864 0.83113338 0.20996249 0.42948818]
  [0.44553685 0.40930492 0.85795258 0.52537988 0.75929232]
  [0.2150231  0.91405876 0.27617818 0.86079784 0.48231296]]

 [[0.78999773 0.08711266 0.20395488 0.72608813 0.46268258]
  [0.49156184 0.37491033 0.28296177 0.86787031 0.21174015]
  [0.46476318 0.58332309 0.94468677 0.28008485 0.37703367]]]


In [23]:
e=a*c

In [24]:
print(e)

[[[0.72300147 0.03352864 0.83113338 0.20996249 0.42948818]
  [0.44553685 0.40930492 0.85795258 0.52537988 0.75929232]
  [0.2150231  0.91405876 0.27617818 0.86079784 0.48231296]]

 [[0.78999773 0.08711266 0.20395488 0.72608813 0.46268258]
  [0.49156184 0.37491033 0.28296177 0.86787031 0.21174015]
  [0.46476318 0.58332309 0.94468677 0.28008485 0.37703367]]]


In [25]:
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [32]:
d_max=np.amax(d)
d_min=np.amin(d)
d_mean=np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9446867743913985
1.0335286415549318
1.5040574499924653


In [35]:
f=np.zeros_like(d)

In [36]:
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [43]:

for a in range(0,2):
    for b in range(0,3):
        for c in range(0,5):
            if d[a,b,c] > d_min and d[a,b,c] < d_mean:
                f[a,b,c] = 25
            elif d[a,b,c] >d_mean and d[a,b,c] <d_max:
                f[a,b,c] = 75
            elif d[a,b,c] == d_mean:
                f[a,b,c] = 50
            elif d[a,b,c] == d_min:
                f[a,b,c] = 0
            elif d[a,b,c] == d_max:
                f[a,b,c] = 100
                
print(f)
    

[[[ 75.   0.  75.  25.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75. 100.  25.  25.]]]


In [46]:
f2=f.astype(str)
for a in range(0,2):
    for b in range(0,3):
        for c in range(0,5):
            if d[a,b,c] > d_min and d[a,b,c] < d_mean:
                f2[a,b,c] = "B"
            elif d[a,b,c] >d_mean and d[a,b,c] <d_max:
                f2[a,b,c] = "D"
            elif d[a,b,c] == d_mean:
                f2[a,b,c] = 'C'
            elif d[a,b,c] == d_min:
                f2[a,b,c] = 'A'
            elif d[a,b,c] == d_max:
                f2[a,b,c] = 'E'
                
print(f2)


[[['D' 'A' 'D' 'B' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'B']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'E' 'B' 'B']]]
